-- MySQL dump 10.13  Distrib 8.0.25, for macos11 (x86_64)
--
-- Host: localhost    Database: nightly_mod
-- ------------------------------------------------------
-- Server version	8.0.25


--
-- Dumping data for table `mongo_structs`
--

REPLACE INTO `mongo_structs` (`id`, `name`, `info`, `is_active`, `scope_id`, `added_on`, `id_str`) VALUES (1,'commChannel','[{\"name\": \"type\", \"dataType\": \"String\"},{\"name\": \"value\", \"dataType\":\"String\"},{\"name\":\"verified\", \"dataType\":\"Option[Boolean]\"}, {\"name\":\"primary\", \"dataType\":\"Option[Boolean]\"}]',1,-1000,'2017-03-01 00:34:12','commChannel_-1000'),
(2,'identifier','[{\"name\": \"type\", \"dataType\": \"String\"},{\"name\": \"value\", \"dataType\" : \"String\"} ]',1,-1000,'2017-03-01 00:34:12','identifier_-1000'),
(3,'auditInfo','[{\"name\": \"_id\", \"dataType\" : \"Option[Long]\"}, {\"name\": \"code\", \"dataType\" : \"string\"}]',1,-1000,'2017-03-02 03:53:21','auditInfo_-1000'),
(4,'profileV2','[{\"name\": \"_id\", \"dataType\" : \"String\"},{\"name\": \"userId\", \"dataType\": \"Long\"},{\"name\": \"orgId\", \"dataType\": \"Long\"},{\"name\": \"source\", \"dataType\": \"String\"},{\"name\": \"accountId\", \"dataType\": \"String\"}, {\"name\": \"lastName\", \"dataType\": \"String\"}, {\"name\": \"firstName\", \"dataType\": \"String\"}, {\"name\": \"autoUpdateTime\", \"dataType\": \"Timestamp\"},{\"name\": \"commChannels\", \"dataType\" : \"List\", \"info\":\"commChannel\"},{\"name\": \"attribution\", \"dataType\": \"attribution_type\"},{\"name\":\"identifiers\",\"dataType\":\"List\",\"info\":\"identifier\"},{\"name\":\"orgSourceId\",\"dataType\":\"Long\"}]',1,-1000,'2017-03-01 00:34:12','profileV2_-1000'),
(5,'extndFieldValue','[{\"name\": \"name\", \"dataType\": \"String\"},{\"name\": \"value\", \"dataType\":\"String\"}]',1,-1000,'2017-03-01 00:34:12','extndFieldValue_-1000'),
(6,'customer_extended_fields','[{\"name\": \"entityId\", \"dataType\": \"Long\"},{\"name\": \"_id\", \"dataType\" : \"String\"},{\"name\": \"orgId\", \"dataType\": \"Long\"},{\"name\": \"source\", \"dataType\": \"String\"},{\"name\": \"entityType\", \"dataType\": \"String\"}, {\"name\": \"autoUpdateTime\", \"dataType\": \"Timestamp\"},{\"name\": \"extendedFields\", \"dataType\" : \"List\", \"info\":\"extndFieldValue\"}]',1,-1000,'2017-03-01 00:34:12','customer_extended_fields_-1000'),
(7,'ffc_data_v2','[{\"name\":\"_id\",\"dataType\":\"String\"},{\"name\":\"deviceId\",\"dataType\":\"Long\"},{\"name\":\"direction\",\"dataType\":\"Long\"},{\"name\":\"eventTime\",\"dataType\":\"Timestamp\"},{\"name\":\"eventType\",\"dataType\":\"String\"},{\"name\":\"orgId\",\"dataType\":\"Long\"},{\"name\":\"source\",\"dataType\":\"String\"},{\"name\":\"storeId\",\"dataType\":\"Long\"},{\"name\":\"tillId\",\"dataType\":\"Long\"},{\"name\":\"zoneId\",\"dataType\":\"Long\"},{\"name\":\"tillName\",\"dataType\":\"String\"},{\"name\":\"storeName\",\"dataType\":\"String\"},{\"name\":\"count\",\"dataType\":\"Long\"},{\"name\":\"inCount\",\"dataType\":\"Long\"},{\"name\":\"outCount\",\"dataType\":\"Long\"},{\"name\":\"autoUpdateTime\",\"dataType\":\"Timestamp\"}]',1,-1000,'2017-10-02 05:31:49','ffc_data_v2_-1000'),
(8,'ffc_groupCount_v2','[{\"name\":\"_id\",\"dataType\":\"String\"},{\"name\":\"deviceId\",\"dataType\":\"Long\"},{\"name\":\"direction\",\"dataType\":\"Long\"},{\"name\":\"eventTime\",\"dataType\":\"Timestamp\"},{\"name\":\"orgId\",\"dataType\":\"Long\"},{\"name\":\"size\",\"dataType\":\"String\"},{\"name\":\"source\",\"dataType\":\"String\"},{\"name\":\"storeId\",\"dataType\":\"Long\"},{\"name\":\"tillId\",\"dataType\":\"Long\"},{\"name\":\"zoneId\",\"dataType\":\"Long\"},{\"name\":\"tillName\",\"dataType\":\"String\"},{\"name\":\"storeName\",\"dataType\":\"String\"},{\"name\":\"eventType\",\"dataType\":\"String\"},{\"name\":\"count\",\"dataType\":\"Long\"},{\"name\":\"autoUpdateTime\",\"dataType\":\"Timestamp\"}]',1,-1000,'2017-10-02 05:31:49','ffc_groupCount_v2_-1000'),
(10,'event_feed','[{\"name\":\"_id\",\"dataType\":\"String\"},{\"name\":\"orgId\",\"dataType\":\"Long\"},{\"name\":\"openId\",\"dataType\":\"String\"},{\"name\":\"eventTime\",\"dataType\":\"Timestamp\"},{\"name\":\"createdBy\",\"dataType\":\"Long\"},{\"name\":\"eventName\",\"dataType\":\"String\"},{\"name\":\"scanId\",\"dataType\":\"Option[String]\"},{\"name\":\"details\",\"dataType\":\"Option[String]\"},{\"name\":\"source\",\"dataType\":\"String\"},{\"name\":\"accountId\",\"dataType\":\"String\"},{\"name\":\"autoUpdateTime\",\"dataType\":\"Timestamp\"},{\"name\":\"eventMode\",\"dataType\":\"Option[Long]\"},{\"name\":\"accountInfoId\",\"dataType\":\"Option[Long]\"},{\"name\":\"clickId\",\"dataType\":\"Option[Long]\"}]',1,-1000,'2018-01-03 08:55:50','event_feed_-1000'),
(11,'click_event','[{\"name\":\"_id\",\"dataType\":\"String\"},{\"name\":\"orgId\",\"dataType\":\"Long\"},{\"name\":\"buttonType\",\"dataType\":\"String\"},{\"name\":\"linkType\",\"dataType\":\"String\"},{\"name\":\"buttonName\",\"dataType\":\"String\"},{\"name\":\"buttonState\",\"dataType\":\"String\"},{\"name\":\"title\",\"dataType\":\"String\"},{\"name\":\"description\",\"dataType\":\"String\"},{\"name\":\"autoUpdateTime\",\"dataType\":\"Timestamp\"},{\"name\":\"source\",\"dataType\":\"String\"},{\"name\":\"sourceAccountId\",\"dataType\":\"String\"},{\"name\":\"buttonId\",\"dataType\":\"Long\"}]',1,-1000,'2018-01-03 08:55:50','click_event_-1000'),
(13,'profile_v2_identifiers','[{\"name\":\"userId\",\"dataType\":\"Long\"},{\"name\":\"orgId\",\"dataType\":\"Long\"},{\"name\":\"source\",\"dataType\":\"String\"},{\"name\":\"accountId\",\"dataType\":\"String\"},{\"name\":\"autoUpdateTime\",\"dataType\":\"Timestamp\"},{\"name\":\"identifiers\",\"dataType\":\"List\",\"info\":\"identifier\"},{\"name\":\"orgSourceId\",\"dataType\":\"Long\"}]',0,-1000,'2018-01-23 11:20:59','profile_v2_identifiers_-1000'),
(14,'attribution_type','[{\"name\": \"modifiedDate\", \"dataType\": \"timestamp\"}, {\"name\": \"createDate\", \"dataType\": \"timestamp\"}, {\"name\": \"createdBy\", \"dataType\": \"auditInfo\"}, {\"name\": \"modifiedBy\", \"dataType\": \"auditInfo\"}]',1,-1000,'2018-02-22 15:28:24','attribution_type_-1000'),
(15,'campaign','[{ \"name\": \"_id\", \"dataType\": \"String\" }, { \"name\": \"campaignId\", \"dataType\": \"Long\" }, { \"name\": \"orgId\", \"dataType\": \"Long\" }, { \"name\": \"orgUnitId\", \"dataType\": \"Long\" }, { \"name\": \"name\", \"dataType\": \"String\" }, { \"name\": \"startDate\", \"dataType\": \"Timestamp\" }, { \"name\": \"endDate\", \"dataType\": \"Timestamp\" }, { \"name\": \"autoUpdateTime\", \"dataType\": \"Timestamp\" }]',1,-1000,'2019-05-31 06:51:30','campaign_-1000'),
(16,'schedule','[{ \"name\": \"type\", \"dataType\": \"String\" }]',1,-1000,'2019-05-31 06:51:30','schedule_-1000'),
(17,'strategy','[{ \"name\": \"type\", \"dataType\": \"String\" }]',1,-1000,'2019-05-31 06:51:30','strategy_-1000'),
(18,'message','[{ \"name\": \"_id\", \"dataType\": \"String\" },{ \"name\": \"type\", \"dataType\": \"String\" },{ \"name\": \"name\", \"dataType\": \"String\" }, { \"name\": \"orgId\", \"dataType\": \"Long\" }, { \"name\": \"campaignId\", \"dataType\": \"Long\" }, { \"name\": \"schedule\", \"dataType\": \"schedule\" }, { \"name\": \"strategy\", \"dataType\": \"strategy\" }, { \"name\": \"autoUpdateTime\", \"dataType\": \"Timestamp\" }]',1,-1000,'2019-05-31 06:51:30','message_-1000'),
(19,'messageContent','[{ \"name\": \"channel\", \"dataType\": \"String\" }]',1,-1000,'2019-05-31 06:51:30','messageContent_-1000'),
(20,'messageVariant','[{ \"name\": \"messageVariantId\", \"dataType\": \"Long\" }, { \"name\": \"orgId\", \"dataType\": \"Long\" }, { \"name\": \"campaignId\", \"dataType\": \"Long\" }, { \"name\": \"messageContent\", \"dataType\": \"messageContent\" }, { \"name\": \"messageId\", \"dataType\": \"String\" }, { \"name\": \"orgUnitId\", \"dataType\": \"Long\" }, { \"name\": \"autoUpdateTime\", \"dataType\": \"Timestamp\" }]',1,-1000,'2019-05-31 06:51:30','messageVariant_-1000'),
(21,'dOutput','[{\"name\":\"orgId\",\"dataType\":\"Option[Long]\"},{\"name\":\"storeId\",\"dataType\":\"Option[Long]\"},{\"name\":\"tillId\",\"dataType\":\"Option[Long]\"},{\"name\":\"deviceId\",\"dataType\":\"Option[Long]\"},{\"name\":\"eventTime\",\"dataType\":\"Timestamp\"},{\"name\":\"eventType\",\"dataType\":\"String\"},{\"name\":\"gender\",\"dataType\":\"Option[String]\"},{\"name\":\"age\",\"dataType\":\"Option[Long]\"},{\"name\":\"smile\",\"dataType\":\"Option[Double]\"},{\"name\":\"dress_texture\",\"dataType\":\"Option[String]\"},{\"name\":\"dress_primaryColor\",\"dataType\":\"Option[String]\"},{\"name\":\"dress_secondaryColor\",\"dataType\":\"Option[String]\"},{\"name\":\"lowerClothes_texture\",\"dataType\":\"Option[String]\"},{\"name\":\"lowerClothes_primaryColor\",\"dataType\":\"Option[String]\"},{\"name\":\"lowerClothes_secondaryColor\",\"dataType\":\"Option[String]\"},{\"name\":\"lowerClothes_class\",\"dataType\":\"Option[String]\"},{\"name\":\"upperClothes_texture\",\"dataType\":\"Option[String]\"},{\"name\":\"upperClothes_primaryColor\",\"dataType\":\"Option[String]\"},{\"name\":\"upperClothes_secondaryColor\",\"dataType\":\"Option[String]\"},{\"name\":\"upperClothes_class\",\"dataType\":\"Option[String]\"},{\"name\":\"moustache\",\"dataType\":\"Option[Double]\"},{\"name\":\"beard\",\"dataType\":\"Option[Double]\"},{\"name\": \"isStaff\", \"dataType\":\"Option[Boolean]\"}, {\"name\":\"timeDurationInSeconds\", \"dataType\":\"Option[Long]\"},{\"name\":\"visitorMappingId\", \"dataType\":\"Option[String]\"}]',1,-1000,'2019-07-26 00:35:53','dOutput_-1000'),
(22,'cvp_v2','[{\"name\":\"_id\",\"dataType\":\"String\"},{\"name\":\"updatedAt\",\"dataType\":\"Timestamp\"},{\"name\":\"createdAt\",\"dataType\":\"Timestamp\"},{\"name\":\"output\",\"dataType\":\"dOutput\"},{\"name\":\"visitorId\",\"dataType\":\"String\"}]',1,-1000,'2019-07-26 00:35:53','cvp_v2_-1000'),
(23,'audience_group','[{\"name\": \"_id\",\"dataType\": \"Long\"},{\"name\":\"name\", \"dataType\": \"String\"},{ \"name\": \"orgId\", \"dataType\": \"Long\"},{ \"name\": \"attribution\", \"dataType\": \"attribution\"},{ \"name\": \"operationType\", \"dataType\": \"Option[String]\"},{ \"name\": \"uuid\", \"dataType\": \"Option[String]\"}]',1,-1000,'2021-03-17 23:00:00','audience_group_-1000'),
(24,'audience_group_version','[{\"name\": \"_id\",\"dataType\": \"Long\"},{  \"name\": \"groupId\", \"dataType\": \"Long\"},{ \"name\": \"orgId\",  \"dataType\": \"Long\"} ,{ \"name\": \"attribution\", \"dataType\": \"attribution\"}]',1,-1000,'2021-03-17 23:00:00','audience_group_version_-1000'),
(25,'attribution','[{\"name\": \"createdOn\", \"dataType\": \"Timestamp\"},{  \"name\": \"createdBy\", \"dataType\": \"Option[Long]\"},{ \"name\": \"lastUpdatedBy\", \"dataType\": \"Option[Long]\"},{ \"name\": \"lastUpdatedOn\",\"dataType\": \"Timestamp\"}]',1,-1000,'2021-03-17 23:00:00','attribution_-1000'),
(26,'control_audience_group_version','[{ \"name\": \"_id\",\"dataType\": \"Long\"},{ \"name\": \"name\", \"dataType\": \"String\"},{ \"name\": \"orgId\", \"dataType\": \"Long\"},{ \"name\": \"attribution\", \"dataType\": \"attribution\"},{\"name\": \"groupId\", \"dataType\": \"Long\"},{ \"name\": \"testGroupVersionId\", \"dataType\": \"Long\"}]',1,-1000,'2021-03-17 23:00:00','control_audience_group_version_-1000'),
(27,'Recurrence','[{\"name\":\"repeatFrequency\",\"dataType\":\"String\"},{\"name\":\"weeklyValues\",\"dataType\":\"List\", \"info\":\"String\"},{\"name\":\"monthlyDayValues\",\"dataType\":\"List\", \"info\":\"Long\"}]',1,-1000,'2021-09-25 04:38:18','Recurrence_-1000'),
(28,'TimeBasedCriteria','[{\"name\":\"startTime\",\"dataType\":\"Timestamp\"},{\"name\":\"durationInHours\",\"dataType\":\"Long\"},{\"name\":\"recurrence\",\"dataType\":\"Recurrence\"}]',1,-1000,'2021-09-25 04:38:18','TimeBasedCriteria_-1000'),
(29,'StoreBasedCriteria','[{\"name\":\"storeType\",\"dataType\":\"String\"},{\"name\":\"operator\",\"dataType\":\"String\"},{\"name\":\"values\",\"dataType\":\"List\", \"info\":\"Long\"}]',1,-1000,'2021-09-25 04:38:18','StoreBasedCriteria_-1000'),
(30,'ProductSelectionCriteria','[{\"name\":\"productEntity\",\"dataType\":\"String\"},{\"name\":\"operator\",\"dataType\":\"String\"},{\"name\":\"values\",\"dataType\":\"List\", \"info\":\"String\"},{\"name\":\"attributeName\",\"dataType\":\"String\"}]',1,-1000,'2021-09-25 04:38:18','ProductSelectionCriteria_-1000'),
(31,'Condition','[{\"name\":\"kpi\",\"dataType\":\"String\"},{\"name\":\"operator\",\"dataType\":\"String\"},{\"name\":\"value\",\"dataType\":\"String\"},{\"name\":\"conditionType\",\"dataType\":\"String\"},{\"name\":\"productSelectionCriteriaList\",\"dataType\":\"List\",\"info\":\"ProductSelectionCriteria\"}]',1,-1000,'2021-09-25 04:38:18','Condition_-1000'),
(33,'RewardImmutable','[{\"name\":\"rewardType\",\"dataType\":\"String\"},{\"name\":\"rewardValueType\",\"dataType\":\"String\"},{\"name\":\"value\",\"dataType\":\"String\"},{\"name\":\"productCondition\",\"dataType\":\"Condition\"}]',1,-1000,'2021-09-25 04:38:18','RewardImmutable_-1000'),
(34,'Reward','[{\"name\":\"rewardImmutable\",\"dataType\":\"RewardImmutable\"}]',1,-1000,'2021-09-25 04:38:18','Reward_-1000'),
(35,'EarningCriteria','[{\"name\":\"earnedFromType\",\"dataType\":\"String\"},{\"name\":\"ruleId\",\"dataType\":\"Long\"},{\"name\":\"milestoneId\",\"dataType\":\"Long\"},{\"name\":\"groupId\",\"dataType\":\"Long\"},{\"name\":\"eventType\",\"dataType\":\"String\"}]',1,-1000,'2021-09-25 04:38:18','EarningCriteria_-1000'),
(36,'Restriction','[{\"name\":\"frequency\",\"dataType\":\"String\"},{\"name\":\"minTimeBetweenRepeat\",\"dataType\":\"Long\"},{\"name\":\"limit\",\"dataType\":\"String\"}]',1,-1000,'2021-09-25 04:38:18','Restriction_-1000'),
(37,'RestrictionKPI','[{\"name\":\"redemption\",\"dataType\":\"Restriction\"},{\"name\":\"transaction\",\"dataType\":\"Restriction\"},{\"name\":\"discount\",\"dataType\":\"Restriction\"}]',1,-1000,'2021-09-25 04:38:18','RestrictionKPI_-1000'),
(38,'PromotionRestriction','[{\"name\":\"customerRestrictionKpi\",\"dataType\":\"RestrictionKPI\"},{\"name\":\"cartRestrictionKpi\",\"dataType\":\"RestrictionKPI\"},{\"name\":\"promotionRestrictionKpi\",\"dataType\":\"RestrictionKPI\"}]',1,-1000,'2021-09-25 04:38:18','PromotionRestriction_-1000'),
(39,'promotionMeta','[{\"name\":\"_id\",\"dataType\":\"String\"},  {\"name\":\"name\",\"dataType\":\"String\"},{\"name\":\"orgId\",\"dataType\":\"Long\"},{\"name\":\"active\",\"dataType\":\"Boolean\"},{\"name\":\"campaignId\",\"dataType\":\"String\"},{\"name\":\"type\",\"dataType\":\"String\"},{\"name\":\"startDate\",\"dataType\":\"Timestamp\"},{\"name\":\"endDate\",\"dataType\":\"Timestamp\"},{\"name\":\"condition\",\"dataType\":\"Condition\"}, {\"name\":\"attribution\",\"dataType\":\"attribution\"},{\"name\":\"reward\",\"dataType\":\"Reward\"}]',1,-1000,'2021-09-25 04:38:18','promotionMeta_-1000'),
(40,'customerIssuedPromotion','[{\"name\":\"_id\",\"dataType\":\"String\"}, {\"name\":\"orgId\",\"dataType\":\"Long\"}, {\"name\":\"customerId\",\"dataType\":\"Long\"}, {\"name\":\"promotionId\",\"dataType\":\"String\"}, {\"name\":\"issuedTime\",\"dataType\":\"Timestamp\"}, {\"name\":\"issuedFromId\",\"dataType\":\"String\"}, {\"name\":\"validTill\",\"dataType\":\"Timestamp\"}, {\"name\":\"attribution\",\"dataType\":\"attribution\"}]',1,-1000,'2021-09-25 04:38:18','customerIssuedPromotion_-1000'),
(41,'EventDetails','[{\"name\":\"_id\",\"dataType\":\"String\"}, {\"name\":\"type\",\"dataType\":\"String\"}]',1,-1000,'2021-09-25 04:38:18','EventDetails_-1000'),
(42,'customerEarnedPromotion','[{\"name\":\"_id\",\"dataType\":\"String\"}, {\"name\":\"orgId\",\"dataType\":\"Long\"}, {\"name\":\"customerId\",\"dataType\":\"Long\"}, {\"name\":\"promotionId\",\"dataType\":\"String\"}, {\"name\":\"earnedFromType\",\"dataType\":\"String\"}, {\"name\":\"eventTime\",\"dataType\":\"Timestamp\"}, {\"name\":\"validTill\",\"dataType\":\"Timestamp\"}, {\"name\":\"active\",\"dataType\":\"Boolean\"}, {\"name\":\"attribution\",\"dataType\":\"attribution\"}]',1,-1000,'2021-09-25 04:38:18','customerEarnedPromotion_-1000'),
(43,'promotionRedemption','[{\"name\":\"_id\",\"dataType\":\"String\"}, {\"name\":\"orgId\",\"dataType\":\"Long\"}, {\"name\":\"customerId\",\"dataType\":\"Long\"}, {\"name\":\"promotionId\",\"dataType\":\"String\"}, {\"name\":\"redemptionDate\",\"dataType\":\"Timestamp\"}, {\"name\":\"transactionIdentifier\",\"dataType\":\"String\"}, {\"name\":\"transactionNumber\",\"dataType\":\"String\"}, {\"name\":\"transactionEntityIdentifier\",\"dataType\":\"String\"}, {\"name\":\"redemptionTill\",\"dataType\":\"Long\"}, {\"name\":\"discount\",\"dataType\":\"String\"}, {\"name\":\"redemptionCount\",\"dataType\":\"Long\"}, {\"name\":\"amount\",\"dataType\":\"String\"},{\"name\":\"attribution\",\"dataType\":\"attribution\"}, {\"name\":\"redemptionType\",\"dataType\":\"String\"}]',1,-1000,'2021-09-25 04:38:18','promotionRedemption_-1000'),
(44,'customerPromotionPreference','[{\"name\":\"_id\",\"dataType\":\"String\"}, {\"name\":\"orgId\",\"dataType\":\"Long\"}, {\"name\":\"customerId\",\"dataType\":\"Long\"}, {\"name\":\"promotionId\",\"dataType\":\"String\"}, {\"name\":\"status\",\"dataType\":\"String\"}, {\"name\":\"attribution\",\"dataType\":\"attribution\"}]',1,-1000,'2021-09-25 04:38:18','customerPromotionPreference_-1000'),
(45,'BiKpiScope','[{ \"name\": \"tag\", \"dataType\": \"String\"},{ \"name\": \"orgId\", \"dataType\": \"Option[Long]\"},{ \"name\": \"verticals\",\"dataType\": \"Option[String]\"}]',1,-1000,'2021-09-08 13:00:00','BiKpiScope_-1000'),
(46,'BiKpi','[{ \"name\": \"_id\",\"dataType\": \"String\"},{ \"name\": \"name\", \"dataType\": \"String\"},{ \"name\": \"scope\", \"dataType\": \"BiKpiScope\"},{ \"name\": \"createdBy\", \"dataType\": \"Option[String]\"},{\"name\": \"createdAt\", \"dataType\": \"Option[java.sql.Timestamp]\"},{\"name\": \"updatedAt\", \"dataType\": \"Option[java.sql.Timestamp]\"},{\"name\": \"isActive\", \"dataType\": \"Boolean\"},{\"name\": \"definition\", \"dataType\": \"Option[String]\"},{\"name\": \"facts\", \"dataType\": \"Option[String]\"},{\"name\": \"parentId\", \"dataType\": \"Option[String]\"}]',1,-1000,'2021-09-08 13:00:00','BiKpi_-1000'),
(47,'BiCategories','[{ \"name\": \"_id\", \"dataType\": \"String\"},{ \"name\": \"name\", \"dataType\": \"String\"},{ \"name\": \"scope\", \"dataType\": \"Option[String]\"},{ \"name\": \"domain\", \"dataType\": \"Option[String]\"},{ \"name\": \"orgId\", \"dataType\": \"String\"},{ \"name\": \"isActive\", \"dataType\": \"String\"},{ \"name\": \"type\", \"dataType\": \"Option[String]\"}]',1,-1000,'2021-09-08 13:00:00','BiCategories_-1000'),
(48,'BiCharts','[{ \"name\": \"_id\", \"dataType\": \"String\"},{ \"name\": \"name\", \"dataType\": \"String\"},{ \"name\": \"scope\", \"dataType\": \"String\"},{ \"name\": \"domain\", \"dataType\": \"String\"},{ \"name\": \"orgId\", \"dataType\": \"String\"},{ \"name\": \"isActive\", \"dataType\": \"String\"},{ \"name\": \"type\", \"dataType\": \"String\"},{ \"name\": \"addedOn\", \"dataType\": \"Option[java.sql.Timestamp]\"},{ \"name\": \"updatedOn\", \"dataType\": \"Option[java.sql.Timestamp]\"},{ \"name\": \"verticals\", \"dataType\": \"Option[String]\"},{ \"name\": \"kpis\", \"dataType\": \"String\"},{ \"name\": \"dimensions\", \"dataType\": \"Option[String]\"},{ \"name\": \"customDimensions\", \"dataType\": \"Option[String]\"}]',1,-1000,'2021-09-08 13:00:00','BiCharts_-1000'),
(49,'BiReports','[{ \"name\": \"_id\", \"dataType\": \"String\"},{ \"name\": \"name\", \"dataType\": \"String\"},{ \"name\": \"scope\", \"dataType\": \"String\"},{ \"name\": \"domain\", \"dataType\": \"Option[String]\"},{ \"name\": \"orgId\", \"dataType\": \"String\"},{ \"name\": \"isActive\", \"dataType\": \"Boolean\"},{ \"name\": \"type\", \"dataType\": \"String\"},{ \"name\": \"addedOn\", \"dataType\": \"Option[java.sql.Timestamp]\"},{ \"name\": \"updatedOn\", \"dataType\": \"Option[java.sql.Timestamp]\"},{ \"name\": \"category\", \"dataType\": \"String\"},{ \"name\": \"createdBy\", \"dataType\": \"Option[String]\"},{ \"name\": \"updatedBy\", \"dataType\": \"Option[String]\"},{ \"name\": \"verticals\", \"dataType\": \"Option[String]\"},{ \"name\": \"charts\", \"dataType\": \"Option[String]\"},{ \"name\": \"description\", \"dataType\": \"Option[String]\"},{ \"name\": \"isPublic\", \"dataType\": \"Boolean\"},{ \"name\": \"filters\", \"dataType\": \"String\"},{ \"name\": \"compareDimension\", \"dataType\": \"Option[String]\"}]',1,-1000,'2021-09-08 13:00:00','BiReports_-1000'),
(50,'BiSchedules','[{ \"name\": \"_id\",\"dataType\": \"String\"},{ \"name\": \"name\", \"dataType\": \"String\"},{ \"name\": \"createdBy\", \"dataType\": \"String\"},{\"name\": \"createdAt\", \"dataType\": \"Timestamp\"},{\"name\": \"updatedAt\", \"dataType\": \"Timestamp\"},{\"name\": \"isActive\", \"dataType\": \"Boolean\"},{\"name\": \"report\", \"dataType\": \"String\"},{\"name\": \"triggerType\", \"dataType\": \"String\"},{\"name\": \"orgId\", \"dataType\": \"Long\"},{\"name\": \"state\", \"dataType\": \"String\"},{\"name\": \"frequency\", \"dataType\": \"String\"}]',1,-1000,'2021-09-08 13:00:00','BiSchedules_-1000'),
(51,'BiScheduleTriggers','[{ \"name\": \"_id\",\"dataType\": \"Long\"},{ \"name\": \"scheduledBy\", \"dataType\": \"String\"},{\"name\": \"createdAt\", \"dataType\": \"Timestamp\"},{\"name\": \"updatedAt\", \"dataType\": \"Timestamp\"},{\"name\": \"isActive\", \"dataType\": \"Boolean\"},{\"name\": \"referenceId\", \"dataType\": \"String\"},{\"name\": \"orgId\", \"dataType\": \"Long\"},{\"name\": \"state\", \"dataType\": \"String\"}]',1,-1000,'2021-09-08 13:00:00','BiScheduleTriggers_-1000'),
(52,'BiScheduleTriggerLogs','[{ \"name\": \"_id\",\"dataType\": \"String\"},{ \"name\": \"scheduledBy\", \"dataType\": \"String\"},{\"name\": \"createdAt\", \"dataType\": \"Timestamp\"},{\"name\": \"updatedAt\", \"dataType\": \"Timestamp\"},{\"name\": \"triggerId\", \"dataType\": \"Long\"},{\"name\": \"orgId\", \"dataType\": \"Long\"},{\"name\": \"state\", \"dataType\": \"String\"}]',1,-1000,'2021-09-08 13:00:00','BiScheduleTriggerLogs_-1000'),
(53,'AudienceFilterDefinitions','[{ \"name\": \"_id\",\"dataType\": \"String\"},{\"name\": \"createdAt\", \"dataType\": \"Option[java.sql.Timestamp]\"},{\"name\": \"updatedAt\", \"dataType\": \"Option[java.sql.Timestamp]\"},{ \"name\": \"name\",\"dataType\": \"String\"},{ \"name\": \"category\",\"dataType\": \"Option[String]\"},{ \"name\": \"scope\",\"dataType\": \"BiKpiScope\"},{ \"name\": \"description\",\"dataType\": \"Option[String]\"}]',1,-1000,'2021-09-08 13:00:00','AudienceFilterDefinitions_-1000'),
(54,'AudienceFilterInstances','[{ \"name\": \"_id\",\"dataType\": \"String\"},{\"name\": \"createdOn\", \"dataType\": \"Timestamp\"},{\"name\": \"createdBy\", \"dataType\": \"String\"},{ \"name\": \"filterName\",\"dataType\": \"String\"},{ \"name\": \"orgId\",\"dataType\": \"Long\"},{ \"name\": \"context\",\"dataType\": \"Option[String]\"},{ \"name\": \"targetBlocks\",\"dataType\": \"String\"}]',1,-1000,'2021-09-08 13:00:00','AudienceFilterInstances_-1000');


-- Dump completed on 2021-10-27 12:15:34
