CREATE TABLE `dimension` (
  `dim_id` int NOT NULL AUTO_INCREMENT,
  `fact_column_link` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dim_table_id` int NOT NULL,
  `scope_id` int NOT NULL DEFAULT '-1000',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `added_on` timestamp NULL DEFAULT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `display_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `description` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `link_type` enum('DIRECT','BRIDGE') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `bridge_table_src_type` enum('DIM','FACT') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `bridge_table_id` int DEFAULT NULL,
  `fact_pk` int DEFAULT NULL,
  `dim_fk` int DEFAULT NULL,
  `dim_id_str` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dim_table_id_str` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `bridge_table_id_str` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fact_pk_str` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dim_fk_str` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`dim_id`),
  UNIQUE KEY `dimension_name` (`name`)
) ENGINE=InnoDB;