CREATE TABLE `fact_fk_constraints` (
  `id` int NOT NULL AUTO_INCREMENT,
  `column_id` int NOT NULL,
  `table_id` int NOT NULL,
  `ordinal_position` int NOT NULL DEFAULT '1',
  `ref_col_id` int NOT NULL DEFAULT '-1',
  `ref_table_id` int NOT NULL DEFAULT '-1',
  `mapping_type` enum('ONE_TO_ONE','ONE_TO_MANY','MANY_TO_ONE','MANY_TO_MANY') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `relattion_type` enum('IS','BELONGS') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `scope_id` int NOT NULL DEFAULT '-1000',
  `added_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_str` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `column_id_str` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `table_id_str` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ref_col_id_str` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ref_table_id_str` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `column_ref_col` (`table_id`,`ref_table_id`,`ordinal_position`)
) ENGINE=InnoDB;